# Project Context - pig-latin-cli

## Project Identity
name: pig-latin-cli
description: A CLI tool that converts English text to Pig Latin
domain: devtools, language-processing

## Technology Stack
language: javascript (ES modules)
runtime: node.js
infrastructure: local CLI

## Architecture Patterns
patterns: functional
structure: single-file CLI application

## Conventions
naming:
  files: kebab-case
  functions: camelCase
  constants: camelCase

testing:
  framework: none configured
  style: manual testing via CLI

## Commands
start: npm start
run: node src/index.js

## Key Directories
src: source code (main entry point)

## Domain Terminology
pig-latin: a language game where words are altered by moving consonants to the end and adding "ay"
vowel-start: words starting with vowels get "way" appended
consonant-start: consonants before first vowel move to end with "ay" appended
